language: php

sudo: required

php:
    - '5.6'
    - '7.0'

git:
    depth: 1

before_install:
    - stty cols 120

install:
    # Composer install
    - composer global require "hirak/prestissimo:^0.3"
    - cd back && composer install
    # Project test init
    - openssl genrsa -out var/jwt/private.test.pem -passout pass:test -aes256 4096
    - openssl rsa -pubout -in var/jwt/private.test.pem -out var/jwt/public.test.pem -passin pass:test
    - php bin/console server:run -p 8000 >/dev/null &

script:
    - composer test-cli

after_script:
    - kill %1 >/dev/null

notifications:
    email: false
    slack: collect-io:AWQ6RxKkkjpYb41abkVxrUqt
