language: php

sudo: required

php:
  - '5.5'
#  - '5.6'
#  - '7.0'
#  - hhvm

git:
    depth: 1

before_install:
    - stty cols 120
    # Install Apache
    #- sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 tree
    - sudo sed -i -e "/DocumentRoot/i\ServerName collect.dev" /etc/apache2/sites-available/default
    - sudo sed -i -e "s#DocumentRoot /var/www#DocumentRoot /home/travis/build/Collect-io/Collect.io/api/web#g" /etc/apache2/sites-available/default
    - echo "127.0.0.1 collect.dev" | sudo tee -a /etc/hosts
    - sudo /etc/init.d/apache2 restart
    # Configure PHP
    - PHP=$TRAVIS_PHP_VERSION
    - if [[ ! $PHP = hhvm* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi
    - echo memory_limit = -1 >> $INI_FILE
    - echo session.gc_probability = 0 >> $INI_FILE
    - echo opcache.enable_cli = 1 >> $INI_FILE
    - if [[ $PHP = 5.* ]]; then (echo yes | pecl install -f apcu-4.0.11 && echo apc.enable_cli = 1 >> $INI_FILE); fi
    - if [[ $PHP = 7.0 ]]; then (echo yes | pecl install -f apcu-5.1.5 && echo apc.enable_cli = 1 >> $INI_FILE); fi

install:
    - cd api && composer install

script:
    - composer test