language: php

sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'

git:
    depth: 1

before_install:
    - stty cols 120

install:
    # Composer install
    - composer global require "hirak/prestissimo:^0.3"
    - cd api && composer install
    # Project test init
    - openssl genrsa -out var/jwt/private.test.pem -passout pass:test -aes256 4096
    - openssl rsa -pubout -in var/jwt/private.test.pem -out var/jwt/public.test.pem -passin pass:test
    - bin/console server:run >/dev/null &

script:
    - composer test

after_script:
    - kill %1 >/dev/null

notifications:
    email: false
