imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:  pdo_sqlite
        user:    tests
        path:    %kernel.root_dir%/behat.db.cache
        charset: utf8

lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/../var/jwt/private.test.pem
    public_key_path:  %kernel.root_dir%/../var/jwt/public.test.pem
    pass_phrase:      test
