NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

tokens:
    type: rest
    resource: AppBundle\Controller\TokenController
    prefix: /api

users:
    type: rest
    resource: AppBundle\Controller\UserController
    prefix: /api

inbox_elements:
    type: rest
    resource: AppBundle\Controller\InboxElementController
    prefix: /api
