# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.jwt_authenticator:
        class: AppBundle\Security\JwtAuthenticator
        autowire: true

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.api_doc.fos_rest_form_errors_parser:
        class: AppBundle\Parser\FOSRestFormErrorsParser
        tags:
            - { name: nelmio_api_doc.extractor.parser, priority: 1 }

    app.flysystem.dropbox:
        class: AppBundle\FlysystemAdapter\Dropbox
        arguments: ["%dropbox_secret%"]
